language: node_js
sudo: false
node_js:
  - '0.12'
  - '4'
  - '5'
env:
  global:
    - secure: "YxoVtF38Cnv+rPZF1WgtZDgQ8g0bZIhhRGs2aGC9ixB+NsvOrxYYHbQ46dxYpc7fbNZE8RSobDwHM/0H/YLYHOAVHj5r7yySh3mG5ptr4k8QNzLrrckruCzwW++wKZL00bafiF9R3e7OjweDR7v9MCOJB7Qa2qQmWhno1yF7+tmmN3Zy4o0ufcPsLZgSx5MUGJQPGNj1j4Gv3iyR8VxkQvo0JB5C0eu9DbR19IXFFHGxH/bl5Vyz4oSpxaD7MaRTUC79a2/mTPNy8SnYYsOq5+wRJCLNvpjSm/iDsFI3fngce0tS6YenadO5LxWJLPqrjBvVoCo/Uh1ncTfEMfAz5oRHefpe/a26RO2NojxYQZHfBGp8hsRyuoscMhwlpuokWfGh9uqj9rbT3TLGUfLmP6OPFJRNiL303nwBAOrhqemADNyOJ0V9QRzqV0VsydL7UUnCiOg1rKFnxxWj0O3T++4/AafRaNZHnNpAIkW9LKw+Afvo12x4REeRrhCUorTH+ZQ3NL/BMrxAwQEiyTKAWqPTur/m28Hdbh5BqPOgn7tV+63L0Ne4Okq8jPWRcHhNomZiLtVeWpt1rrlhK8C1Uq2bw+NgB7fwb72V3xGVY7MQnGyTPHdq1TGR4CfQ/Nqk9Vab927v+La79TlWXdeqOGSGKLuf9sIp9z3SjV+uO4g="
    - secure: "W9s55SoBp9INEwS2Va2mGRCsFz+6DN8lAlEJ2OnS8U7amFaVXfNoqzO0ZP7NrYyJlZny8s4k3k1YhLLgu/SHHTlkgOId7UHKL+CcpRksczcavgQSqDrFKGe1M5GOQCqhw70C4UJkWCE2Mz90N1JYNnpNN3bKEY5gkleoMLqhWxQUjQjrrhZD9yOOWitnK81Se9rzGgKBs3PCXga1stoR28kYdHwVMq8I/VUJxBdP4SVdFyXbjbC9KQICObzNZIDHkDanKRly4egWY6hRhXTWFoaLMQZpDOwGg7PxnYM1cnN6314tnk1tdaaldhUghg5ZERa81hvjy84h5H15LiMiiqBNkcgLGzGeOZZ2J9xG2mmPPeCH9vRVqQONSHg2iIQAv2XfU+lp1/BDnNkTt8oKJSGjbsn4TIIeiQhzVjHpTi24Jcuqld18B7l8b28AvWRLQK2Z+qZ6W6YSI9nldsCN23gSoqbmsp7dPm2LwRI9xwH9K1Uh27cZb0Sun9/3Gg+yxaofy6QcCdogsENbxU2bzsKO1PR7VXgLGipRIqaEl1QxiERRYOwk4MGfA+N8XRq0poPYzCM2ddpHM7IU60oQjKnpY9kKkUe/h8gIFACYUtMolCw+RW8jCTMlSKI6uycT3wHJsWKaugKee7fPNvDNsFpoXalHYmYqUbU28hj8LSY="
before_install:
  # Log HTTP requests
  - npm config set loglevel http
  # Set up xvfb for headless Firefox testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - time npm install
