language: node_js
sudo: false
node_js:
  - '0.12'
  - '4'
  - '5'
env:
  global:
    - secure: aj4r9sWjH1Di8tstvWCZS2DqTLFnMgIduX85/YzqwQKK3CuWffbFrVwo6xMuSLDdl4w9MRCcSrZ3ZfO/JEHHBN9xh4NQXbwcj2wT4g2Lnt08eKyGCIP4vHviahqyMGg+0cEXJkl8QORN5ts3alEoJcL8xDkKFhinJc7sxjD54mBSkJZYUyMSsOgM3OpuMwaSYgU5Aq+HlegD8N68X4ezQeSqeBLwNLuf+S6she3sLu7uKA75PkcZAUQ9b34Gy606SKFCiNrnNHC3JneEcD61Kdwf6UoR3VPen/SU1VBmaEufHcV0XAedaekkFY1YOaxZ0ClKwA2ehzY5sjBuJxUup3s32bedkzoq/lvD3HClzDykVA8pjWdpJRS/TXEo68toRnKwFe72mh2I2Ml4eJegSu6RRITd0GOfkdjut1HHpduIz2f039h7rYruR8Pm0Pi1N9aJ3b6FV5h7mXF+JR8QWjHklbw/MGIrvTzKjLYXSN9Vo7sUBGzyH8XK6vy/Eg2K0uHnakORCx5zS7kB1uidFy/cQ+UtuOm4518DnMVtaIqQouWsfTxe62fafUozH/BU1q3nXTGbjQGIi9lR6NbKVw6c9JBosVjN2pkHbkMx3t0JINV+0DkoYKrZSLShEYf3dHgGmsCMQgNodeVTFrU/4+GOl2aWKjsqN0ubk4TJ3Dw=
    - secure: m4V3krPDqQYGK4HVXqIqSBRUFtEn0CHpeRzttf/f8p84rv6HiY6Ss5FG8NmOopOtreSbaeuPvSQGZgwyQ2ohubgnXhtK4FntbyeKQnQfMRUMGoM8MxcZO7/b/ATXaqJ3lK2+DkP7ghcfNKn5siyo+NGv42DBzVCprKmFLvMv2chAHOnPvD/wOyort/hzp/rojP6W6QNU+ZV842vDCa1E7HUPI+5U7odmVjNg4UVGPX+6RBMaElik1AU7bNi4UXWKafrD9ND7eb7OHiW0bVGnGeoI4UkeDM+hLSkqtHKU9JxLCXSTnIHbhjE27JvMWZTCN19WWUo9la4Gc8g84nz3rT2DWg5O2z3qGz7g5UzoYZ/CasHc53SsmwI6WDr4JonSFyesYluZhGasONPH4pAz9NI9sq8VYZJcyfjC10lA4gSLsbu3jX3KQSn4Vx06nIfBbKEl8Vxm6gYL4EzYZZrArqHo5+FCBO5mSiYhiNmBoneDAmm9tDqemthtn8KYDWMma4WxC/F/NwNOnFsXGIEjz41z/3QZ13fS+Dzl/BgAKmrqwcmh0JhDWN2DGonbZXV3H/HmsQvO6Hdt73WDObBUjnutfJfy7mts7YUgppIPFPFjJE11O3oLHS9uQ36tNqnHbPImfIMKUaPjYDBriyg/ik0Vp4nSI5m82JAjb6f4TbA=
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  # Log HTTP requests
  - npm config set loglevel http
  # Set up xvfb for headless Firefox testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - time npm install
